version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodbmessenger"
        environment:
        - MONGO_LOG_DIR=/dev/null
        ports:
        - 27017:27017
        volumes:
        - /home/gokul/messengerMongo:/data/db